#yoni/functions/drop_entity_inventory
replaceitem entity @s slot.inventory 0 air 1 0
replaceitem entity @s slot.inventory 1 air 1 0
replaceitem entity @s slot.inventory 2 air 1 0
replaceitem entity @s slot.inventory 3 air 1 0
replaceitem entity @s slot.inventory 4 air 1 0
replaceitem entity @s slot.inventory 5 air 1 0
replaceitem entity @s slot.inventory 6 air 1 0
replaceitem entity @s slot.inventory 7 air 1 0
replaceitem entity @s slot.inventory 8 air 1 0
replaceitem entity @s slot.inventory 9 air 1 0
replaceitem entity @s slot.inventory 10 air 1 0
replaceitem entity @s slot.inventory 11 air 1 0
replaceitem entity @s slot.inventory 12 air 1 0
replaceitem entity @s slot.inventory 13 air 1 0
replaceitem entity @s slot.inventory 14 air 1 0
replaceitem entity @s slot.inventory 15 air 1 0
replaceitem entity @s slot.inventory 16 air 1 0
replaceitem entity @s slot.inventory 17 air 1 0
replaceitem entity @s slot.inventory 18 air 1 0
replaceitem entity @s slot.inventory 19 air 1 0
replaceitem entity @s slot.inventory 20 air 1 0
replaceitem entity @s slot.inventory 21 air 1 0
replaceitem entity @s slot.inventory 22 air 1 0
replaceitem entity @s slot.inventory 23 air 1 0
replaceitem entity @s slot.inventory 24 air 1 0
replaceitem entity @s slot.inventory 25 air 1 0
replaceitem entity @s slot.inventory 26 air 1 0
