#yoni/functions/lock_player_enderchest
replaceitem entity @s slot.enderchest 0 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 1 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 2 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 3 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 4 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 5 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 6 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 7 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 8 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 9 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 10 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 11 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 12 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 13 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 14 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 15 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 16 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 17 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 18 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 19 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 20 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 21 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 22 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 23 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 24 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 25 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 26 keep yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
