replaceitem entity @s slot.hotbar 0 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.hotbar 1 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.hotbar 2 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.hotbar 3 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.hotbar 4 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.hotbar 5 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.hotbar 6 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.hotbar 7 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.hotbar 8 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
