scoreboard objectives add ef:resistance dummy
scoreboard objectives add ef:strength dummy
scoreboard objectives add ef:night_vision dummy
scoreboard objectives add ef:slowness dummy
scoreboard objectives add ef:speed dummy
scoreboard objectives add ef:mining dummy
scoreboard objectives add ef:saturation dummy
scoreboard objectives add ef:blindness dummy
scoreboard objectives add ef:darkness dummy
scoreboard objectives add ef:weakness dummy
scoreboard objectives add ef:jump_boost dummy
scoreboard objectives add ef:instant_health dummy
