#operation/clear/block
replaceitem block ~ ~ ~ slot.container 0 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 1 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 2 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 3 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 4 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 5 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 6 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 7 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 8 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 9 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 10 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 11 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 12 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 13 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 14 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 15 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 16 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 17 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 18 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 19 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 20 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 21 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 22 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 23 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 24 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 25 destroy air 1 0
replaceitem block ~ ~ ~ slot.container 26 destroy air 1 0
