#yoni/guxi/alive/damage
# 恢复血量
effect @s instant_health 1 255 true
# 47x^5
execute @s[scores={health=59}] ~ ~ ~ scoreboard players remove @s guxi:energy 47
execute @s[scores={health=58}] ~ ~ ~ scoreboard players remove @s guxi:energy 1504
execute @s[scores={health=57}] ~ ~ ~ scoreboard players remove @s guxi:energy 11421
execute @s[scores={health=56}] ~ ~ ~ scoreboard players remove @s guxi:energy 48128
execute @s[scores={health=55}] ~ ~ ~ scoreboard players remove @s guxi:energy 146875
execute @s[scores={health=54}] ~ ~ ~ scoreboard players remove @s guxi:energy 365472
execute @s[scores={health=53}] ~ ~ ~ scoreboard players remove @s guxi:energy 789929
execute @s[scores={health=52}] ~ ~ ~ scoreboard players remove @s guxi:energy 1540096
execute @s[scores={health=51}] ~ ~ ~ scoreboard players remove @s guxi:energy 2775303
execute @s[scores={health=50}] ~ ~ ~ scoreboard players remove @s guxi:energy 4700000
execute @s[scores={health=49}] ~ ~ ~ scoreboard players remove @s guxi:energy 7569397
execute @s[scores={health=48}] ~ ~ ~ scoreboard players remove @s guxi:energy 11695104
execute @s[scores={health=47}] ~ ~ ~ scoreboard players remove @s guxi:energy 17450771
execute @s[scores={health=46}] ~ ~ ~ scoreboard players remove @s guxi:energy 25277728
execute @s[scores={health=45}] ~ ~ ~ scoreboard players remove @s guxi:energy 35690625
execute @s[scores={health=44}] ~ ~ ~ scoreboard players remove @s guxi:energy 49283072
execute @s[scores={health=43}] ~ ~ ~ scoreboard players remove @s guxi:energy 66733279
execute @s[scores={health=42}] ~ ~ ~ scoreboard players remove @s guxi:energy 88809696
execute @s[scores={health=41}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={health=41}] ~ ~ ~ scoreboard players remove @s guxi:energy 16376653
execute @s[scores={health=40}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={health=40}] ~ ~ ~ scoreboard players remove @s guxi:energy 50400000
execute @s[scores={health=39}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={health=39}] ~ ~ ~ scoreboard players remove @s guxi:energy 91952747
execute @s[scores={health=38}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={health=38}] ~ ~ ~ scoreboard players remove @s guxi:energy 42220704
execute @s[scores={health=37}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={health=37}] ~ ~ ~ scoreboard players remove @s guxi:energy 2508121
execute @s[scores={health=36}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={health=36}] ~ ~ ~ scoreboard players remove @s guxi:energy 74243328
execute @s[scores={health=35}] ~ ~ ~ scoreboard players remove @s guxi:energies 4
execute @s[scores={health=35}] ~ ~ ~ scoreboard players remove @s guxi:energy 58984375
execute @s[scores={health=34}] ~ ~ ~ scoreboard players remove @s guxi:energies 5
execute @s[scores={health=34}] ~ ~ ~ scoreboard players remove @s guxi:energy 58424672
execute @s[scores={health=33}] ~ ~ ~ scoreboard players remove @s guxi:energies 6
execute @s[scores={health=33}] ~ ~ ~ scoreboard players remove @s guxi:energy 74398629
execute @s[scores={health=32}] ~ ~ ~ scoreboard players remove @s guxi:energies 8
execute @s[scores={health=32}] ~ ~ ~ scoreboard players remove @s guxi:energy 8887296
execute @s[scores={health=31}] ~ ~ ~ scoreboard players remove @s guxi:energies 9
execute @s[scores={health=31}] ~ ~ ~ scoreboard players remove @s guxi:energy 64024003
execute @s[scores={health=30}] ~ ~ ~ scoreboard players remove @s guxi:energies 11
execute @s[scores={health=30}] ~ ~ ~ scoreboard players remove @s guxi:energy 42100000
execute @s[scores={health=29}] ~ ~ ~ scoreboard players remove @s guxi:energies 13
execute @s[scores={health=29}] ~ ~ ~ scoreboard players remove @s guxi:energy 45570097
execute @s[scores={health=28}] ~ ~ ~ scoreboard players remove @s guxi:energies 15
execute @s[scores={health=28}] ~ ~ ~ scoreboard players remove @s guxi:energy 77058304
execute @s[scores={health=27}] ~ ~ ~ scoreboard players remove @s guxi:energies 18
execute @s[scores={health=27}] ~ ~ ~ scoreboard players remove @s guxi:energy 39363471
execute @s[scores={health=26}] ~ ~ ~ scoreboard players remove @s guxi:energies 21
execute @s[scores={health=26}] ~ ~ ~ scoreboard players remove @s guxi:energy 35464928
execute @s[scores={health=25}] ~ ~ ~ scoreboard players remove @s guxi:energies 24
execute @s[scores={health=25}] ~ ~ ~ scoreboard players remove @s guxi:energy 68528125
execute @s[scores={health=24}] ~ ~ ~ scoreboard players remove @s guxi:energies 28
execute @s[scores={health=24}] ~ ~ ~ scoreboard players remove @s guxi:energy 41910272
execute @s[scores={health=23}] ~ ~ ~ scoreboard players remove @s guxi:energies 32
execute @s[scores={health=23}] ~ ~ ~ scoreboard players remove @s guxi:energy 59165979
execute @s[scores={health=22}] ~ ~ ~ scoreboard players remove @s guxi:energies 37
execute @s[scores={health=22}] ~ ~ ~ scoreboard players remove @s guxi:energy 24052896
execute @s[scores={health=21}] ~ ~ ~ scoreboard players remove @s guxi:energies 42
execute @s[scores={health=21}] ~ ~ ~ scoreboard players remove @s guxi:energy 40537353
execute @s[scores={health=20}] ~ ~ ~ scoreboard players remove @s guxi:energies 48
execute @s[scores={health=20}] ~ ~ ~ scoreboard players remove @s guxi:energy 12800000
execute @s[scores={health=19}] ~ ~ ~ scoreboard players remove @s guxi:energies 54
execute @s[scores={health=19}] ~ ~ ~ scoreboard players remove @s guxi:energy 45241447
execute @s[scores={health=18}] ~ ~ ~ scoreboard players remove @s guxi:energies 61
execute @s[scores={health=18}] ~ ~ ~ scoreboard players remove @s guxi:energy 42487904
execute @s[scores={health=17}] ~ ~ ~ scoreboard players remove @s guxi:energies 69
execute @s[scores={health=17}] ~ ~ ~ scoreboard players remove @s guxi:energy 9396821
execute @s[scores={health=16}] ~ ~ ~ scoreboard players remove @s guxi:energies 77
execute @s[scores={health=16}] ~ ~ ~ scoreboard players remove @s guxi:energy 51062528
execute @s[scores={health=15}] ~ ~ ~ scoreboard players remove @s guxi:energies 86
execute @s[scores={health=15}] ~ ~ ~ scoreboard players remove @s guxi:energy 72821875
execute @s[scores={health=14}] ~ ~ ~ scoreboard players remove @s guxi:energies 96
execute @s[scores={health=14}] ~ ~ ~ scoreboard players remove @s guxi:energy 80259872
execute @s[scores={health=13}] ~ ~ ~ scoreboard players remove @s guxi:energies 107
execute @s[scores={health=13}] ~ ~ ~ scoreboard players remove @s guxi:energy 79215329
execute @s[scores={health=12}] ~ ~ ~ scoreboard players remove @s guxi:energies 119
execute @s[scores={health=12}] ~ ~ ~ scoreboard players remove @s guxi:energy 75786496
execute @s[scores={health=11}] ~ ~ ~ scoreboard players remove @s guxi:energies 132
execute @s[scores={health=11}] ~ ~ ~ scoreboard players remove @s guxi:energy 76336703
execute @s[scores={health=10}] ~ ~ ~ scoreboard players remove @s guxi:energies 146
execute @s[scores={health=10}] ~ ~ ~ scoreboard players remove @s guxi:energy 87500000
execute @s[scores={health=9}] ~ ~ ~ scoreboard players remove @s guxi:energies 162
execute @s[scores={health=9}] ~ ~ ~ scoreboard players remove @s guxi:energy 16186797
execute @s[scores={health=8}] ~ ~ ~ scoreboard players remove @s guxi:energies 178
execute @s[scores={health=8}] ~ ~ ~ scoreboard players remove @s guxi:energy 69589504
execute @s[scores={health=7}] ~ ~ ~ scoreboard players remove @s guxi:energies 196
execute @s[scores={health=7}] ~ ~ ~ scoreboard players remove @s guxi:energy 55188171
execute @s[scores={health=6}] ~ ~ ~ scoreboard players remove @s guxi:energies 215
execute @s[scores={health=6}] ~ ~ ~ scoreboard players remove @s guxi:energy 80756128
execute @s[scores={health=5}] ~ ~ ~ scoreboard players remove @s guxi:energies 236
execute @s[scores={health=5}] ~ ~ ~ scoreboard players remove @s guxi:energy 54365625
execute @s[scores={health=4}] ~ ~ ~ scoreboard players remove @s guxi:energies 258
execute @s[scores={health=4}] ~ ~ ~ scoreboard players remove @s guxi:energy 84393472
execute @s[scores={health=3}] ~ ~ ~ scoreboard players remove @s guxi:energies 282
execute @s[scores={health=3}] ~ ~ ~ scoreboard players remove @s guxi:energy 79526679
execute @s[scores={health=2}] ~ ~ ~ scoreboard players remove @s guxi:energies 308
execute @s[scores={health=2}] ~ ~ ~ scoreboard players remove @s guxi:energy 48768096
execute @s[scores={health=1}] ~ ~ ~ scoreboard players remove @s guxi:energies 336
execute @s[scores={health=1}] ~ ~ ~ scoreboard players remove @s guxi:energy 1442053
execute @s[scores={health=0}] ~ ~ ~ scoreboard players remove @s guxi:energies 365
execute @s[scores={health=0}] ~ ~ ~ scoreboard players remove @s guxi:energy 47200000
