execute if score @s guxi:ef_speed matches -1 run effect @s slowness 3 0 true
execute if score @s guxi:ef_speed matches -2 run effect @s slowness 3 1 true
execute if score @s guxi:ef_speed matches -3 run effect @s slowness 3 2 true
execute if score @s guxi:ef_speed matches -4 run effect @s slowness 3 3 true
execute if score @s guxi:ef_speed matches -5 run effect @s slowness 3 4 true
execute if score @s guxi:ef_speed matches -6 run effect @s slowness 3 5 true
execute if score @s guxi:ef_speed matches -7 run effect @s slowness 3 6 true
execute if score @s guxi:ef_speed matches -8 run effect @s slowness 3 7 true
execute if score @s guxi:ef_speed matches -9 run effect @s slowness 3 8 true
execute if score @s guxi:ef_speed matches ..-10 run effect @s slowness 3 9 true

execute if score @s guxi:ef_speed matches 20.. run effect @s speed 3 19 true
execute if score @s guxi:ef_speed matches 19 run effect @s speed 3 18 true
execute if score @s guxi:ef_speed matches 18 run effect @s speed 3 17 true
execute if score @s guxi:ef_speed matches 17 run effect @s speed 3 16 true
execute if score @s guxi:ef_speed matches 16 run effect @s speed 3 15 true
execute if score @s guxi:ef_speed matches 15 run effect @s speed 3 14 true
execute if score @s guxi:ef_speed matches 14 run effect @s speed 3 13 true
execute if score @s guxi:ef_speed matches 13 run effect @s speed 3 12 true
execute if score @s guxi:ef_speed matches 12 run effect @s speed 3 11 true
execute if score @s guxi:ef_speed matches 11 run effect @s speed 3 10 true
execute if score @s guxi:ef_speed matches 10 run effect @s speed 3 9 true
execute if score @s guxi:ef_speed matches 9 run effect @s speed 3 8 true
execute if score @s guxi:ef_speed matches 8 run effect @s speed 3 7 true
execute if score @s guxi:ef_speed matches 7 run effect @s speed 3 6 true
execute if score @s guxi:ef_speed matches 6 run effect @s speed 3 5 true
execute if score @s guxi:ef_speed matches 5 run effect @s speed 3 4 true
execute if score @s guxi:ef_speed matches 4 run effect @s speed 3 3 true
execute if score @s guxi:ef_speed matches 3 run effect @s speed 3 2 true
execute if score @s guxi:ef_speed matches 2 run effect @s speed 3 1 true
execute if score @s guxi:ef_speed matches 1 run effect @s speed 3 0 true
