#lostenergyfunc
#损失血量时丢失的能量:lostEnergy=32*disHealth^5

execute @s[scores={guxi:disHealth=1}] ~ ~ ~ scoreboard players remove @s guxi:energy 32
execute @s[scores={guxi:disHealth=2}] ~ ~ ~ scoreboard players remove @s guxi:energy 1024
execute @s[scores={guxi:disHealth=3}] ~ ~ ~ scoreboard players remove @s guxi:energy 7776
execute @s[scores={guxi:disHealth=4}] ~ ~ ~ scoreboard players remove @s guxi:energy 32768
execute @s[scores={guxi:disHealth=5}] ~ ~ ~ scoreboard players remove @s guxi:energy 100000
execute @s[scores={guxi:disHealth=6}] ~ ~ ~ scoreboard players remove @s guxi:energy 248832
execute @s[scores={guxi:disHealth=7}] ~ ~ ~ scoreboard players remove @s guxi:energy 537824
execute @s[scores={guxi:disHealth=8}] ~ ~ ~ scoreboard players remove @s guxi:energy 1048576
execute @s[scores={guxi:disHealth=9}] ~ ~ ~ scoreboard players remove @s guxi:energy 1889568
execute @s[scores={guxi:disHealth=10}] ~ ~ ~ scoreboard players remove @s guxi:energy 3200000
execute @s[scores={guxi:disHealth=11}] ~ ~ ~ scoreboard players remove @s guxi:energy 5153632
execute @s[scores={guxi:disHealth=12}] ~ ~ ~ scoreboard players remove @s guxi:energy 7962624
execute @s[scores={guxi:disHealth=13}] ~ ~ ~ scoreboard players remove @s guxi:energy 11881376
execute @s[scores={guxi:disHealth=14}] ~ ~ ~ scoreboard players remove @s guxi:energy 17210368
execute @s[scores={guxi:disHealth=15}] ~ ~ ~ scoreboard players remove @s guxi:energy 24300000
execute @s[scores={guxi:disHealth=16}] ~ ~ ~ scoreboard players remove @s guxi:energy 33554432
execute @s[scores={guxi:disHealth=17}] ~ ~ ~ scoreboard players remove @s guxi:energy 45435424
execute @s[scores={guxi:disHealth=18}] ~ ~ ~ scoreboard players remove @s guxi:energy 60466176
execute @s[scores={guxi:disHealth=19}] ~ ~ ~ scoreboard players remove @s guxi:energy 79235168
execute @s[scores={guxi:disHealth=20}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:disHealth=20}] ~ ~ ~ scoreboard players remove @s guxi:energy 2400000
execute @s[scores={guxi:disHealth=21}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:disHealth=21}] ~ ~ ~ scoreboard players remove @s guxi:energy 30691232
execute @s[scores={guxi:disHealth=22}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:disHealth=22}] ~ ~ ~ scoreboard players remove @s guxi:energy 64916224
execute @s[scores={guxi:disHealth=23}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:disHealth=23}] ~ ~ ~ scoreboard players remove @s guxi:energy 5962976
execute @s[scores={guxi:disHealth=24}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:disHealth=24}] ~ ~ ~ scoreboard players remove @s guxi:energy 54803968
execute @s[scores={guxi:disHealth=25}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:disHealth=25}] ~ ~ ~ scoreboard players remove @s guxi:energy 12500000
execute @s[scores={guxi:disHealth=26}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:disHealth=26}] ~ ~ ~ scoreboard players remove @s guxi:energy 80204032
execute @s[scores={guxi:disHealth=27}] ~ ~ ~ scoreboard players remove @s guxi:energies 4
execute @s[scores={guxi:disHealth=27}] ~ ~ ~ scoreboard players remove @s guxi:energy 59165024
execute @s[scores={guxi:disHealth=28}] ~ ~ ~ scoreboard players remove @s guxi:energies 5
execute @s[scores={guxi:disHealth=28}] ~ ~ ~ scoreboard players remove @s guxi:energy 50731776
execute @s[scores={guxi:disHealth=29}] ~ ~ ~ scoreboard players remove @s guxi:energies 6
execute @s[scores={guxi:disHealth=29}] ~ ~ ~ scoreboard players remove @s guxi:energy 56356768
execute @s[scores={guxi:disHealth=30}] ~ ~ ~ scoreboard players remove @s guxi:energies 7
execute @s[scores={guxi:disHealth=30}] ~ ~ ~ scoreboard players remove @s guxi:energy 77600000
execute @s[scores={guxi:disHealth=31}] ~ ~ ~ scoreboard players remove @s guxi:energies 9
execute @s[scores={guxi:disHealth=31}] ~ ~ ~ scoreboard players remove @s guxi:energy 16132832
execute @s[scores={guxi:disHealth=32}] ~ ~ ~ scoreboard players remove @s guxi:energies 10
execute @s[scores={guxi:disHealth=32}] ~ ~ ~ scoreboard players remove @s guxi:energy 73741824
execute @s[scores={guxi:disHealth=33}] ~ ~ ~ scoreboard players remove @s guxi:energies 12
execute @s[scores={guxi:disHealth=33}] ~ ~ ~ scoreboard players remove @s guxi:energy 52332576
execute @s[scores={guxi:disHealth=34}] ~ ~ ~ scoreboard players remove @s guxi:energies 14
execute @s[scores={guxi:disHealth=34}] ~ ~ ~ scoreboard players remove @s guxi:energy 53933568
execute @s[scores={guxi:disHealth=35}] ~ ~ ~ scoreboard players remove @s guxi:energies 16
execute @s[scores={guxi:disHealth=35}] ~ ~ ~ scoreboard players remove @s guxi:energy 80700000
execute @s[scores={guxi:disHealth=36}] ~ ~ ~ scoreboard players remove @s guxi:energies 19
execute @s[scores={guxi:disHealth=36}] ~ ~ ~ scoreboard players remove @s guxi:energy 34917632
execute @s[scores={guxi:disHealth=37}] ~ ~ ~ scoreboard players remove @s guxi:energies 22
execute @s[scores={guxi:disHealth=37}] ~ ~ ~ scoreboard players remove @s guxi:energy 19006624
execute @s[scores={guxi:disHealth=38}] ~ ~ ~ scoreboard players remove @s guxi:energies 25
execute @s[scores={guxi:disHealth=38}] ~ ~ ~ scoreboard players remove @s guxi:energy 35525376
execute @s[scores={guxi:disHealth=39}] ~ ~ ~ scoreboard players remove @s guxi:energies 28
execute @s[scores={guxi:disHealth=39}] ~ ~ ~ scoreboard players remove @s guxi:energy 87174368
execute @s[scores={guxi:disHealth=40}] ~ ~ ~ scoreboard players remove @s guxi:energies 32
execute @s[scores={guxi:disHealth=40}] ~ ~ ~ scoreboard players remove @s guxi:energy 76800000
execute @s[scores={guxi:disHealth=41}] ~ ~ ~ scoreboard players remove @s guxi:energies 37
execute @s[scores={guxi:disHealth=41}] ~ ~ ~ scoreboard players remove @s guxi:energy 7398432
execute @s[scores={guxi:disHealth=42}] ~ ~ ~ scoreboard players remove @s guxi:energies 41
execute @s[scores={guxi:disHealth=42}] ~ ~ ~ scoreboard players remove @s guxi:energy 82119424
execute @s[scores={guxi:disHealth=43}] ~ ~ ~ scoreboard players remove @s guxi:energies 47
execute @s[scores={guxi:disHealth=43}] ~ ~ ~ scoreboard players remove @s guxi:energy 4270176
execute @s[scores={guxi:disHealth=44}] ~ ~ ~ scoreboard players remove @s guxi:energies 52
execute @s[scores={guxi:disHealth=44}] ~ ~ ~ scoreboard players remove @s guxi:energy 77319168
execute @s[scores={guxi:disHealth=45}] ~ ~ ~ scoreboard players remove @s guxi:energies 59
execute @s[scores={guxi:disHealth=45}] ~ ~ ~ scoreboard players remove @s guxi:energy 4900000
execute @s[scores={guxi:disHealth=46}] ~ ~ ~ scoreboard players remove @s guxi:energies 65
execute @s[scores={guxi:disHealth=46}] ~ ~ ~ scoreboard players remove @s guxi:energy 90815232
execute @s[scores={guxi:disHealth=47}] ~ ~ ~ scoreboard players remove @s guxi:energies 73
execute @s[scores={guxi:disHealth=47}] ~ ~ ~ scoreboard players remove @s guxi:energy 39040224
execute @s[scores={guxi:disHealth=48}] ~ ~ ~ scoreboard players remove @s guxi:energies 81
execute @s[scores={guxi:disHealth=48}] ~ ~ ~ scoreboard players remove @s guxi:energy 53726976
execute @s[scores={guxi:disHealth=49}] ~ ~ ~ scoreboard players remove @s guxi:energies 90
execute @s[scores={guxi:disHealth=49}] ~ ~ ~ scoreboard players remove @s guxi:energy 39207968
execute @s[scores={guxi:disHealth=50}] ~ ~ ~ scoreboard players remove @s guxi:energies 100
execute @s[scores={guxi:disHealth=50}] ~ ~ ~ scoreboard players remove @s guxi:energy 0
execute @s[scores={guxi:disHealth=51}] ~ ~ ~ scoreboard players remove @s guxi:energies 110
execute @s[scores={guxi:disHealth=51}] ~ ~ ~ scoreboard players remove @s guxi:energy 40808032
execute @s[scores={guxi:disHealth=52}] ~ ~ ~ scoreboard players remove @s guxi:energies 121
execute @s[scores={guxi:disHealth=52}] ~ ~ ~ scoreboard players remove @s guxi:energy 66529024
execute @s[scores={guxi:disHealth=53}] ~ ~ ~ scoreboard players remove @s guxi:energies 133
execute @s[scores={guxi:disHealth=53}] ~ ~ ~ scoreboard players remove @s guxi:energy 82255776
execute @s[scores={guxi:disHealth=54}] ~ ~ ~ scoreboard players remove @s guxi:energies 146
execute @s[scores={guxi:disHealth=54}] ~ ~ ~ scoreboard players remove @s guxi:energy 93280768
execute @s[scores={guxi:disHealth=55}] ~ ~ ~ scoreboard players remove @s guxi:energies 161
execute @s[scores={guxi:disHealth=55}] ~ ~ ~ scoreboard players remove @s guxi:energy 5100000
execute @s[scores={guxi:disHealth=56}] ~ ~ ~ scoreboard players remove @s guxi:energies 176
execute @s[scores={guxi:disHealth=56}] ~ ~ ~ scoreboard players remove @s guxi:energy 23416832
execute @s[scores={guxi:disHealth=57}] ~ ~ ~ scoreboard players remove @s guxi:energies 192
execute @s[scores={guxi:disHealth=57}] ~ ~ ~ scoreboard players remove @s guxi:energy 54145824
execute @s[scores={guxi:disHealth=58}] ~ ~ ~ scoreboard players remove @s guxi:energies 210
execute @s[scores={guxi:disHealth=58}] ~ ~ ~ scoreboard players remove @s guxi:energy 3416576
execute @s[scores={guxi:disHealth=59}] ~ ~ ~ scoreboard players remove @s guxi:energies 228
execute @s[scores={guxi:disHealth=59}] ~ ~ ~ scoreboard players remove @s guxi:energy 77577568
execute @s[scores={guxi:disHealth=60}] ~ ~ ~ scoreboard players remove @s guxi:energies 248
execute @s[scores={guxi:disHealth=60}] ~ ~ ~ scoreboard players remove @s guxi:energy 83200000

