#damage
execute @s[scores={guxi:lostHealth=1}] ~ ~ ~ scoreboard players remove @s guxi:energy 89
execute @s[scores={guxi:lostHealth=2}] ~ ~ ~ scoreboard players remove @s guxi:energy 1424
execute @s[scores={guxi:lostHealth=3}] ~ ~ ~ scoreboard players remove @s guxi:energy 7209
execute @s[scores={guxi:lostHealth=4}] ~ ~ ~ scoreboard players remove @s guxi:energy 22784
execute @s[scores={guxi:lostHealth=5}] ~ ~ ~ scoreboard players remove @s guxi:energy 55625
execute @s[scores={guxi:lostHealth=6}] ~ ~ ~ scoreboard players remove @s guxi:energy 115344
execute @s[scores={guxi:lostHealth=7}] ~ ~ ~ scoreboard players remove @s guxi:energy 213689
execute @s[scores={guxi:lostHealth=8}] ~ ~ ~ scoreboard players remove @s guxi:energy 364544
execute @s[scores={guxi:lostHealth=9}] ~ ~ ~ scoreboard players remove @s guxi:energy 583929
execute @s[scores={guxi:lostHealth=10}] ~ ~ ~ scoreboard players remove @s guxi:energy 890000
execute @s[scores={guxi:lostHealth=11}] ~ ~ ~ scoreboard players remove @s guxi:energy 1303049
execute @s[scores={guxi:lostHealth=12}] ~ ~ ~ scoreboard players remove @s guxi:energy 1845504
execute @s[scores={guxi:lostHealth=13}] ~ ~ ~ scoreboard players remove @s guxi:energy 2541929
execute @s[scores={guxi:lostHealth=14}] ~ ~ ~ scoreboard players remove @s guxi:energy 3419024
execute @s[scores={guxi:lostHealth=15}] ~ ~ ~ scoreboard players remove @s guxi:energy 4505625
execute @s[scores={guxi:lostHealth=16}] ~ ~ ~ scoreboard players remove @s guxi:energy 5832704
execute @s[scores={guxi:lostHealth=17}] ~ ~ ~ scoreboard players remove @s guxi:energy 7433369
execute @s[scores={guxi:lostHealth=18}] ~ ~ ~ scoreboard players remove @s guxi:energy 9342864
execute @s[scores={guxi:lostHealth=19}] ~ ~ ~ scoreboard players remove @s guxi:energy 11598569
execute @s[scores={guxi:lostHealth=20}] ~ ~ ~ scoreboard players remove @s guxi:energy 14240000
execute @s[scores={guxi:lostHealth=21}] ~ ~ ~ scoreboard players remove @s guxi:energy 17308809
execute @s[scores={guxi:lostHealth=22}] ~ ~ ~ scoreboard players remove @s guxi:energy 20848784
execute @s[scores={guxi:lostHealth=23}] ~ ~ ~ scoreboard players remove @s guxi:energy 24905849
execute @s[scores={guxi:lostHealth=24}] ~ ~ ~ scoreboard players remove @s guxi:energy 29528064
execute @s[scores={guxi:lostHealth=25}] ~ ~ ~ scoreboard players remove @s guxi:energy 34765625
execute @s[scores={guxi:lostHealth=26}] ~ ~ ~ scoreboard players remove @s guxi:energy 40670864
execute @s[scores={guxi:lostHealth=27}] ~ ~ ~ scoreboard players remove @s guxi:energy 47298249
execute @s[scores={guxi:lostHealth=28}] ~ ~ ~ scoreboard players remove @s guxi:energy 54704384
execute @s[scores={guxi:lostHealth=29}] ~ ~ ~ scoreboard players remove @s guxi:energy 62948009
execute @s[scores={guxi:lostHealth=30}] ~ ~ ~ scoreboard players remove @s guxi:energy 72090000
execute @s[scores={guxi:lostHealth=31}] ~ ~ ~ scoreboard players remove @s guxi:energy 82193369
execute @s[scores={guxi:lostHealth=32}] ~ ~ ~ scoreboard players remove @s guxi:energy 93323264
execute @s[scores={guxi:lostHealth=33}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lostHealth=33}] ~ ~ ~ scoreboard players remove @s guxi:energy 5546969
execute @s[scores={guxi:lostHealth=34}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lostHealth=34}] ~ ~ ~ scoreboard players remove @s guxi:energy 18933904
execute @s[scores={guxi:lostHealth=35}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lostHealth=35}] ~ ~ ~ scoreboard players remove @s guxi:energy 33555625
execute @s[scores={guxi:lostHealth=36}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lostHealth=36}] ~ ~ ~ scoreboard players remove @s guxi:energy 49485824
execute @s[scores={guxi:lostHealth=37}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lostHealth=37}] ~ ~ ~ scoreboard players remove @s guxi:energy 66800329
execute @s[scores={guxi:lostHealth=38}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lostHealth=38}] ~ ~ ~ scoreboard players remove @s guxi:energy 85577104
execute @s[scores={guxi:lostHealth=39}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:lostHealth=39}] ~ ~ ~ scoreboard players remove @s guxi:energy 5896249
execute @s[scores={guxi:lostHealth=40}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:lostHealth=40}] ~ ~ ~ scoreboard players remove @s guxi:energy 27840000
execute @s[scores={guxi:lostHealth=41}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:lostHealth=41}] ~ ~ ~ scoreboard players remove @s guxi:energy 51492729
execute @s[scores={guxi:lostHealth=42}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:lostHealth=42}] ~ ~ ~ scoreboard players remove @s guxi:energy 76940944
execute @s[scores={guxi:lostHealth=43}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:lostHealth=43}] ~ ~ ~ scoreboard players remove @s guxi:energy 4273289
execute @s[scores={guxi:lostHealth=44}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:lostHealth=44}] ~ ~ ~ scoreboard players remove @s guxi:energy 33580544
execute @s[scores={guxi:lostHealth=45}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:lostHealth=45}] ~ ~ ~ scoreboard players remove @s guxi:energy 64955625
execute @s[scores={guxi:lostHealth=46}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:lostHealth=46}] ~ ~ ~ scoreboard players remove @s guxi:energy 98493584
execute @s[scores={guxi:lostHealth=47}] ~ ~ ~ scoreboard players remove @s guxi:energies 4
execute @s[scores={guxi:lostHealth=47}] ~ ~ ~ scoreboard players remove @s guxi:energy 34291609
execute @s[scores={guxi:lostHealth=48}] ~ ~ ~ scoreboard players remove @s guxi:energies 4
execute @s[scores={guxi:lostHealth=48}] ~ ~ ~ scoreboard players remove @s guxi:energy 72449024
execute @s[scores={guxi:lostHealth=49}] ~ ~ ~ scoreboard players remove @s guxi:energies 5
execute @s[scores={guxi:lostHealth=49}] ~ ~ ~ scoreboard players remove @s guxi:energy 13067289
execute @s[scores={guxi:lostHealth=50}] ~ ~ ~ scoreboard players remove @s guxi:energies 5
execute @s[scores={guxi:lostHealth=50}] ~ ~ ~ scoreboard players remove @s guxi:energy 56250000
execute @s[scores={guxi:lostHealth=51}] ~ ~ ~ scoreboard players remove @s guxi:energies 6
execute @s[scores={guxi:lostHealth=51}] ~ ~ ~ scoreboard players remove @s guxi:energy 2102889
execute @s[scores={guxi:lostHealth=52}] ~ ~ ~ scoreboard players remove @s guxi:energies 6
execute @s[scores={guxi:lostHealth=52}] ~ ~ ~ scoreboard players remove @s guxi:energy 50733824
execute @s[scores={guxi:lostHealth=53}] ~ ~ ~ scoreboard players remove @s guxi:energies 7
execute @s[scores={guxi:lostHealth=53}] ~ ~ ~ scoreboard players remove @s guxi:energy 2252809
execute @s[scores={guxi:lostHealth=54}] ~ ~ ~ scoreboard players remove @s guxi:energies 7
execute @s[scores={guxi:lostHealth=54}] ~ ~ ~ scoreboard players remove @s guxi:energy 56771984
execute @s[scores={guxi:lostHealth=55}] ~ ~ ~ scoreboard players remove @s guxi:energies 8
execute @s[scores={guxi:lostHealth=55}] ~ ~ ~ scoreboard players remove @s guxi:energy 14405625
execute @s[scores={guxi:lostHealth=56}] ~ ~ ~ scoreboard players remove @s guxi:energies 8
execute @s[scores={guxi:lostHealth=56}] ~ ~ ~ scoreboard players remove @s guxi:energy 75270144
execute @s[scores={guxi:lostHealth=57}] ~ ~ ~ scoreboard players remove @s guxi:energies 9
execute @s[scores={guxi:lostHealth=57}] ~ ~ ~ scoreboard players remove @s guxi:energy 39484089
execute @s[scores={guxi:lostHealth=58}] ~ ~ ~ scoreboard players remove @s guxi:energies 10
execute @s[scores={guxi:lostHealth=58}] ~ ~ ~ scoreboard players remove @s guxi:energy 7168144
execute @s[scores={guxi:lostHealth=59}] ~ ~ ~ scoreboard players remove @s guxi:energies 10
execute @s[scores={guxi:lostHealth=59}] ~ ~ ~ scoreboard players remove @s guxi:energy 78445129
execute @s[scores={guxi:lostHealth=60}] ~ ~ ~ scoreboard players remove @s guxi:energies 11
execute @s[scores={guxi:lostHealth=60}] ~ ~ ~ scoreboard players remove @s guxi:energy 53440000

