#cureenergyfunc
#回复耗能:cureEnergy=disHealth^5
#每次回复量: 2

effect @s instant_health 1 0 false
execute @s[scores={guxi:disHealth=1}] ~ ~ ~ scoreboard players remove @s guxi:energy 1
execute @s[scores={guxi:disHealth=2}] ~ ~ ~ scoreboard players remove @s guxi:energy 32
execute @s[scores={guxi:disHealth=3}] ~ ~ ~ scoreboard players remove @s guxi:energy 243
execute @s[scores={guxi:disHealth=4}] ~ ~ ~ scoreboard players remove @s guxi:energy 1024
execute @s[scores={guxi:disHealth=5}] ~ ~ ~ scoreboard players remove @s guxi:energy 3125
execute @s[scores={guxi:disHealth=6}] ~ ~ ~ scoreboard players remove @s guxi:energy 7776
execute @s[scores={guxi:disHealth=7}] ~ ~ ~ scoreboard players remove @s guxi:energy 16807
execute @s[scores={guxi:disHealth=8}] ~ ~ ~ scoreboard players remove @s guxi:energy 32768
execute @s[scores={guxi:disHealth=9}] ~ ~ ~ scoreboard players remove @s guxi:energy 59049
execute @s[scores={guxi:disHealth=10}] ~ ~ ~ scoreboard players remove @s guxi:energy 100000
execute @s[scores={guxi:disHealth=11}] ~ ~ ~ scoreboard players remove @s guxi:energy 161051
execute @s[scores={guxi:disHealth=12}] ~ ~ ~ scoreboard players remove @s guxi:energy 248832
execute @s[scores={guxi:disHealth=13}] ~ ~ ~ scoreboard players remove @s guxi:energy 371293
execute @s[scores={guxi:disHealth=14}] ~ ~ ~ scoreboard players remove @s guxi:energy 537824
execute @s[scores={guxi:disHealth=15}] ~ ~ ~ scoreboard players remove @s guxi:energy 759375
execute @s[scores={guxi:disHealth=16}] ~ ~ ~ scoreboard players remove @s guxi:energy 1048576
execute @s[scores={guxi:disHealth=17}] ~ ~ ~ scoreboard players remove @s guxi:energy 1419857
execute @s[scores={guxi:disHealth=18}] ~ ~ ~ scoreboard players remove @s guxi:energy 1889568
execute @s[scores={guxi:disHealth=19}] ~ ~ ~ scoreboard players remove @s guxi:energy 2476099
execute @s[scores={guxi:disHealth=20}] ~ ~ ~ scoreboard players remove @s guxi:energy 3200000
execute @s[scores={guxi:disHealth=21}] ~ ~ ~ scoreboard players remove @s guxi:energy 4084101
execute @s[scores={guxi:disHealth=22}] ~ ~ ~ scoreboard players remove @s guxi:energy 5153632
execute @s[scores={guxi:disHealth=23}] ~ ~ ~ scoreboard players remove @s guxi:energy 6436343
execute @s[scores={guxi:disHealth=24}] ~ ~ ~ scoreboard players remove @s guxi:energy 7962624
execute @s[scores={guxi:disHealth=25}] ~ ~ ~ scoreboard players remove @s guxi:energy 9765625
execute @s[scores={guxi:disHealth=26}] ~ ~ ~ scoreboard players remove @s guxi:energy 11881376
execute @s[scores={guxi:disHealth=27}] ~ ~ ~ scoreboard players remove @s guxi:energy 14348907
execute @s[scores={guxi:disHealth=28}] ~ ~ ~ scoreboard players remove @s guxi:energy 17210368
execute @s[scores={guxi:disHealth=29}] ~ ~ ~ scoreboard players remove @s guxi:energy 20511149
execute @s[scores={guxi:disHealth=30}] ~ ~ ~ scoreboard players remove @s guxi:energy 24300000
execute @s[scores={guxi:disHealth=31}] ~ ~ ~ scoreboard players remove @s guxi:energy 28629151
execute @s[scores={guxi:disHealth=32}] ~ ~ ~ scoreboard players remove @s guxi:energy 33554432
execute @s[scores={guxi:disHealth=33}] ~ ~ ~ scoreboard players remove @s guxi:energy 39135393
execute @s[scores={guxi:disHealth=34}] ~ ~ ~ scoreboard players remove @s guxi:energy 45435424
execute @s[scores={guxi:disHealth=35}] ~ ~ ~ scoreboard players remove @s guxi:energy 52521875
execute @s[scores={guxi:disHealth=36}] ~ ~ ~ scoreboard players remove @s guxi:energy 60466176
execute @s[scores={guxi:disHealth=37}] ~ ~ ~ scoreboard players remove @s guxi:energy 69343957
execute @s[scores={guxi:disHealth=38}] ~ ~ ~ scoreboard players remove @s guxi:energy 79235168
execute @s[scores={guxi:disHealth=39}] ~ ~ ~ scoreboard players remove @s guxi:energy 90224199
execute @s[scores={guxi:disHealth=40}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:disHealth=40}] ~ ~ ~ scoreboard players remove @s guxi:energy 2400000
execute @s[scores={guxi:disHealth=41}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:disHealth=41}] ~ ~ ~ scoreboard players remove @s guxi:energy 15856201
execute @s[scores={guxi:disHealth=42}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:disHealth=42}] ~ ~ ~ scoreboard players remove @s guxi:energy 30691232
execute @s[scores={guxi:disHealth=43}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:disHealth=43}] ~ ~ ~ scoreboard players remove @s guxi:energy 47008443
execute @s[scores={guxi:disHealth=44}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:disHealth=44}] ~ ~ ~ scoreboard players remove @s guxi:energy 64916224
execute @s[scores={guxi:disHealth=45}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:disHealth=45}] ~ ~ ~ scoreboard players remove @s guxi:energy 84528125
execute @s[scores={guxi:disHealth=46}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:disHealth=46}] ~ ~ ~ scoreboard players remove @s guxi:energy 5962976
execute @s[scores={guxi:disHealth=47}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:disHealth=47}] ~ ~ ~ scoreboard players remove @s guxi:energy 29345007
execute @s[scores={guxi:disHealth=48}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:disHealth=48}] ~ ~ ~ scoreboard players remove @s guxi:energy 54803968
execute @s[scores={guxi:disHealth=49}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:disHealth=49}] ~ ~ ~ scoreboard players remove @s guxi:energy 82475249
execute @s[scores={guxi:disHealth=50}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:disHealth=50}] ~ ~ ~ scoreboard players remove @s guxi:energy 12500000
execute @s[scores={guxi:disHealth=51}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:disHealth=51}] ~ ~ ~ scoreboard players remove @s guxi:energy 45025251
execute @s[scores={guxi:disHealth=52}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:disHealth=52}] ~ ~ ~ scoreboard players remove @s guxi:energy 80204032
execute @s[scores={guxi:disHealth=53}] ~ ~ ~ scoreboard players remove @s guxi:energies 4
execute @s[scores={guxi:disHealth=53}] ~ ~ ~ scoreboard players remove @s guxi:energy 18195493
execute @s[scores={guxi:disHealth=54}] ~ ~ ~ scoreboard players remove @s guxi:energies 4
execute @s[scores={guxi:disHealth=54}] ~ ~ ~ scoreboard players remove @s guxi:energy 59165024
execute @s[scores={guxi:disHealth=55}] ~ ~ ~ scoreboard players remove @s guxi:energies 5
execute @s[scores={guxi:disHealth=55}] ~ ~ ~ scoreboard players remove @s guxi:energy 3284375
execute @s[scores={guxi:disHealth=56}] ~ ~ ~ scoreboard players remove @s guxi:energies 5
execute @s[scores={guxi:disHealth=56}] ~ ~ ~ scoreboard players remove @s guxi:energy 50731776
execute @s[scores={guxi:disHealth=57}] ~ ~ ~ scoreboard players remove @s guxi:energies 6
execute @s[scores={guxi:disHealth=57}] ~ ~ ~ scoreboard players remove @s guxi:energy 1692057
execute @s[scores={guxi:disHealth=58}] ~ ~ ~ scoreboard players remove @s guxi:energies 6
execute @s[scores={guxi:disHealth=58}] ~ ~ ~ scoreboard players remove @s guxi:energy 56356768
execute @s[scores={guxi:disHealth=59}] ~ ~ ~ scoreboard players remove @s guxi:energies 7
execute @s[scores={guxi:disHealth=59}] ~ ~ ~ scoreboard players remove @s guxi:energy 14924299
