#damage
execute @s[scores={guxi:lastHealth=1}] ~ ~ ~ scoreboard players remove @s guxi:energy 89
execute @s[scores={guxi:lastHealth=2}] ~ ~ ~ scoreboard players remove @s guxi:energy 1424
execute @s[scores={guxi:lastHealth=3}] ~ ~ ~ scoreboard players remove @s guxi:energy 7209
execute @s[scores={guxi:lastHealth=4}] ~ ~ ~ scoreboard players remove @s guxi:energy 22784
execute @s[scores={guxi:lastHealth=5}] ~ ~ ~ scoreboard players remove @s guxi:energy 55625
execute @s[scores={guxi:lastHealth=6}] ~ ~ ~ scoreboard players remove @s guxi:energy 115344
execute @s[scores={guxi:lastHealth=7}] ~ ~ ~ scoreboard players remove @s guxi:energy 213689
execute @s[scores={guxi:lastHealth=8}] ~ ~ ~ scoreboard players remove @s guxi:energy 364544
execute @s[scores={guxi:lastHealth=9}] ~ ~ ~ scoreboard players remove @s guxi:energy 583929
execute @s[scores={guxi:lastHealth=10}] ~ ~ ~ scoreboard players remove @s guxi:energy 890000
execute @s[scores={guxi:lastHealth=11}] ~ ~ ~ scoreboard players remove @s guxi:energy 1303049
execute @s[scores={guxi:lastHealth=12}] ~ ~ ~ scoreboard players remove @s guxi:energy 1845504
execute @s[scores={guxi:lastHealth=13}] ~ ~ ~ scoreboard players remove @s guxi:energy 2541929
execute @s[scores={guxi:lastHealth=14}] ~ ~ ~ scoreboard players remove @s guxi:energy 3419024
execute @s[scores={guxi:lastHealth=15}] ~ ~ ~ scoreboard players remove @s guxi:energy 4505625
execute @s[scores={guxi:lastHealth=16}] ~ ~ ~ scoreboard players remove @s guxi:energy 5832704
execute @s[scores={guxi:lastHealth=17}] ~ ~ ~ scoreboard players remove @s guxi:energy 7433369
execute @s[scores={guxi:lastHealth=18}] ~ ~ ~ scoreboard players remove @s guxi:energy 9342864
execute @s[scores={guxi:lastHealth=19}] ~ ~ ~ scoreboard players remove @s guxi:energy 11598569
execute @s[scores={guxi:lastHealth=20}] ~ ~ ~ scoreboard players remove @s guxi:energy 14240000
execute @s[scores={guxi:lastHealth=21}] ~ ~ ~ scoreboard players remove @s guxi:energy 17308809
execute @s[scores={guxi:lastHealth=22}] ~ ~ ~ scoreboard players remove @s guxi:energy 20848784
execute @s[scores={guxi:lastHealth=23}] ~ ~ ~ scoreboard players remove @s guxi:energy 24905849
execute @s[scores={guxi:lastHealth=24}] ~ ~ ~ scoreboard players remove @s guxi:energy 29528064
execute @s[scores={guxi:lastHealth=25}] ~ ~ ~ scoreboard players remove @s guxi:energy 34765625
execute @s[scores={guxi:lastHealth=26}] ~ ~ ~ scoreboard players remove @s guxi:energy 40670864
execute @s[scores={guxi:lastHealth=27}] ~ ~ ~ scoreboard players remove @s guxi:energy 47298249
execute @s[scores={guxi:lastHealth=28}] ~ ~ ~ scoreboard players remove @s guxi:energy 54704384
execute @s[scores={guxi:lastHealth=29}] ~ ~ ~ scoreboard players remove @s guxi:energy 62948009
execute @s[scores={guxi:lastHealth=30}] ~ ~ ~ scoreboard players remove @s guxi:energy 72090000
execute @s[scores={guxi:lastHealth=31}] ~ ~ ~ scoreboard players remove @s guxi:energy 82193369
execute @s[scores={guxi:lastHealth=32}] ~ ~ ~ scoreboard players remove @s guxi:energy 93323264
execute @s[scores={guxi:lastHealth=33}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lastHealth=33}] ~ ~ ~ scoreboard players remove @s guxi:energy 5546969
execute @s[scores={guxi:lastHealth=34}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lastHealth=34}] ~ ~ ~ scoreboard players remove @s guxi:energy 18933904
execute @s[scores={guxi:lastHealth=35}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lastHealth=35}] ~ ~ ~ scoreboard players remove @s guxi:energy 33555625
execute @s[scores={guxi:lastHealth=36}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lastHealth=36}] ~ ~ ~ scoreboard players remove @s guxi:energy 49485824
execute @s[scores={guxi:lastHealth=37}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lastHealth=37}] ~ ~ ~ scoreboard players remove @s guxi:energy 66800329
execute @s[scores={guxi:lastHealth=38}] ~ ~ ~ scoreboard players remove @s guxi:energies 1
execute @s[scores={guxi:lastHealth=38}] ~ ~ ~ scoreboard players remove @s guxi:energy 85577104
execute @s[scores={guxi:lastHealth=39}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:lastHealth=39}] ~ ~ ~ scoreboard players remove @s guxi:energy 5896249
execute @s[scores={guxi:lastHealth=40}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:lastHealth=40}] ~ ~ ~ scoreboard players remove @s guxi:energy 27840000
execute @s[scores={guxi:lastHealth=41}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:lastHealth=41}] ~ ~ ~ scoreboard players remove @s guxi:energy 51492729
execute @s[scores={guxi:lastHealth=42}] ~ ~ ~ scoreboard players remove @s guxi:energies 2
execute @s[scores={guxi:lastHealth=42}] ~ ~ ~ scoreboard players remove @s guxi:energy 76940944
execute @s[scores={guxi:lastHealth=43}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:lastHealth=43}] ~ ~ ~ scoreboard players remove @s guxi:energy 4273289
execute @s[scores={guxi:lastHealth=44}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:lastHealth=44}] ~ ~ ~ scoreboard players remove @s guxi:energy 33580544
execute @s[scores={guxi:lastHealth=45}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:lastHealth=45}] ~ ~ ~ scoreboard players remove @s guxi:energy 64955625
execute @s[scores={guxi:lastHealth=46}] ~ ~ ~ scoreboard players remove @s guxi:energies 3
execute @s[scores={guxi:lastHealth=46}] ~ ~ ~ scoreboard players remove @s guxi:energy 98493584
execute @s[scores={guxi:lastHealth=47}] ~ ~ ~ scoreboard players remove @s guxi:energies 4
execute @s[scores={guxi:lastHealth=47}] ~ ~ ~ scoreboard players remove @s guxi:energy 34291609
execute @s[scores={guxi:lastHealth=48}] ~ ~ ~ scoreboard players remove @s guxi:energies 4
execute @s[scores={guxi:lastHealth=48}] ~ ~ ~ scoreboard players remove @s guxi:energy 72449024
execute @s[scores={guxi:lastHealth=49}] ~ ~ ~ scoreboard players remove @s guxi:energies 5
execute @s[scores={guxi:lastHealth=49}] ~ ~ ~ scoreboard players remove @s guxi:energy 13067289
execute @s[scores={guxi:lastHealth=50}] ~ ~ ~ scoreboard players remove @s guxi:energies 5
execute @s[scores={guxi:lastHealth=50}] ~ ~ ~ scoreboard players remove @s guxi:energy 56250000
execute @s[scores={guxi:lastHealth=51}] ~ ~ ~ scoreboard players remove @s guxi:energies 6
execute @s[scores={guxi:lastHealth=51}] ~ ~ ~ scoreboard players remove @s guxi:energy 2102889
execute @s[scores={guxi:lastHealth=52}] ~ ~ ~ scoreboard players remove @s guxi:energies 6
execute @s[scores={guxi:lastHealth=52}] ~ ~ ~ scoreboard players remove @s guxi:energy 50733824
execute @s[scores={guxi:lastHealth=53}] ~ ~ ~ scoreboard players remove @s guxi:energies 7
execute @s[scores={guxi:lastHealth=53}] ~ ~ ~ scoreboard players remove @s guxi:energy 2252809
execute @s[scores={guxi:lastHealth=54}] ~ ~ ~ scoreboard players remove @s guxi:energies 7
execute @s[scores={guxi:lastHealth=54}] ~ ~ ~ scoreboard players remove @s guxi:energy 56771984
execute @s[scores={guxi:lastHealth=55}] ~ ~ ~ scoreboard players remove @s guxi:energies 8
execute @s[scores={guxi:lastHealth=55}] ~ ~ ~ scoreboard players remove @s guxi:energy 14405625
execute @s[scores={guxi:lastHealth=56}] ~ ~ ~ scoreboard players remove @s guxi:energies 8
execute @s[scores={guxi:lastHealth=56}] ~ ~ ~ scoreboard players remove @s guxi:energy 75270144
execute @s[scores={guxi:lastHealth=57}] ~ ~ ~ scoreboard players remove @s guxi:energies 9
execute @s[scores={guxi:lastHealth=57}] ~ ~ ~ scoreboard players remove @s guxi:energy 39484089
execute @s[scores={guxi:lastHealth=58}] ~ ~ ~ scoreboard players remove @s guxi:energies 10
execute @s[scores={guxi:lastHealth=58}] ~ ~ ~ scoreboard players remove @s guxi:energy 7168144
execute @s[scores={guxi:lastHealth=59}] ~ ~ ~ scoreboard players remove @s guxi:energies 10
execute @s[scores={guxi:lastHealth=59}] ~ ~ ~ scoreboard players remove @s guxi:energy 78445129
execute @s[scores={guxi:lastHealth=60}] ~ ~ ~ scoreboard players remove @s guxi:energies 11
execute @s[scores={guxi:lastHealth=60}] ~ ~ ~ scoreboard players remove @s guxi:energy 53440000

