execute if score @s guxi:ef_mining matches -1 run effect @s mining_fatigue 3 0 true
execute if score @s guxi:ef_mining matches -2 run effect @s mining_fatigue 3 1 true
execute if score @s guxi:ef_mining matches -3 run effect @s mining_fatigue 3 2 true
execute if score @s guxi:ef_mining matches -4 run effect @s mining_fatigue 3 3 true
execute if score @s guxi:ef_mining matches -5 run effect @s mining_fatigue 3 4 true
execute if score @s guxi:ef_mining matches -6 run effect @s mining_fatigue 3 5 true
execute if score @s guxi:ef_mining matches -7 run effect @s mining_fatigue 3 6 true
execute if score @s guxi:ef_mining matches -8 run effect @s mining_fatigue 3 7 true
execute if score @s guxi:ef_mining matches -9 run effect @s mining_fatigue 3 8 true
execute if score @s guxi:ef_mining matches ..-10 run effect @s mining_fatigue 3 9 true

execute if score @s guxi:ef_mining matches 20.. run effect @s haste 3 19 true
execute if score @s guxi:ef_mining matches 19 run effect @s haste 3 18 true
execute if score @s guxi:ef_mining matches 18 run effect @s haste 3 17 true
execute if score @s guxi:ef_mining matches 17 run effect @s haste 3 16 true
execute if score @s guxi:ef_mining matches 16 run effect @s haste 3 15 true
execute if score @s guxi:ef_mining matches 15 run effect @s haste 3 14 true
execute if score @s guxi:ef_mining matches 14 run effect @s haste 3 13 true
execute if score @s guxi:ef_mining matches 13 run effect @s haste 3 12 true
execute if score @s guxi:ef_mining matches 12 run effect @s haste 3 11 true
execute if score @s guxi:ef_mining matches 11 run effect @s haste 3 10 true
execute if score @s guxi:ef_mining matches 10 run effect @s haste 3 9 true
execute if score @s guxi:ef_mining matches 9 run effect @s haste 3 8 true
execute if score @s guxi:ef_mining matches 8 run effect @s haste 3 7 true
execute if score @s guxi:ef_mining matches 7 run effect @s haste 3 6 true
execute if score @s guxi:ef_mining matches 6 run effect @s haste 3 5 true
execute if score @s guxi:ef_mining matches 5 run effect @s haste 3 4 true
execute if score @s guxi:ef_mining matches 4 run effect @s haste 3 3 true
execute if score @s guxi:ef_mining matches 3 run effect @s haste 3 2 true
execute if score @s guxi:ef_mining matches 2 run effect @s haste 3 1 true
execute if score @s guxi:ef_mining matches 1 run effect @s haste 3 0 true
