function entity/position/getRotationX

scoreboard players operation @s var_0 = @s pos:rotate_x

execute if score @s var_0 matches -90 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -90 ~
execute if score @s var_0 matches -89 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -89.26 ~
execute if score @s var_0 matches -88 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -88.53 ~
execute if score @s var_0 matches -87 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -87.80 ~
execute if score @s var_0 matches -86 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -87.07 ~
execute if score @s var_0 matches -85 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -86.34 ~
execute if score @s var_0 matches -84 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -85.60 ~
execute if score @s var_0 matches -83 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -84.87 ~
execute if score @s var_0 matches -82 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -84.14 ~
execute if score @s var_0 matches -81 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -83.41 ~
execute if score @s var_0 matches -80 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -82.67 ~
execute if score @s var_0 matches -79 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -81.94 ~
execute if score @s var_0 matches -78 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -81.21 ~
execute if score @s var_0 matches -77 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -80.47 ~
execute if score @s var_0 matches -76 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -79.74 ~
execute if score @s var_0 matches -75 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -79.00 ~
execute if score @s var_0 matches -74 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -78.27 ~
execute if score @s var_0 matches -73 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -77.53 ~
execute if score @s var_0 matches -72 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -76.80 ~
execute if score @s var_0 matches -71 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -76.06 ~
execute if score @s var_0 matches -70 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -75.32 ~
execute if score @s var_0 matches -69 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -74.59 ~
execute if score @s var_0 matches -68 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -73.85 ~
execute if score @s var_0 matches -67 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -73.11 ~
execute if score @s var_0 matches -66 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -72.37 ~
execute if score @s var_0 matches -65 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -71.63 ~
execute if score @s var_0 matches -64 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -70.89 ~
execute if score @s var_0 matches -63 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -70.25 ~
execute if score @s var_0 matches -62 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -69.40 ~
execute if score @s var_0 matches -61 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -68.66 ~
execute if score @s var_0 matches -60 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -67.92 ~
execute if score @s var_0 matches -59 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -67.17 ~
execute if score @s var_0 matches -58 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -66.43 ~
execute if score @s var_0 matches -57 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -65.68 ~
execute if score @s var_0 matches -56 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -64.93 ~
execute if score @s var_0 matches -55 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -64.18 ~
execute if score @s var_0 matches -54 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -63.43 ~
execute if score @s var_0 matches -53 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -62.68 ~
execute if score @s var_0 matches -52 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -61.93 ~
execute if score @s var_0 matches -51 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -61.18 ~
execute if score @s var_0 matches -50 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -6 ~
execute if score @s var_0 matches -49 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -59.67 ~
execute if score @s var_0 matches -48 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -58.91 ~
execute if score @s var_0 matches -47 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -58.15 ~
execute if score @s var_0 matches -46 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -57.39 ~
execute if score @s var_0 matches -45 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -56.63 ~
execute if score @s var_0 matches -44 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -55.87 ~
execute if score @s var_0 matches -43 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -55.10 ~
execute if score @s var_0 matches -42 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -54.34 ~
execute if score @s var_0 matches -41 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -53.57 ~
execute if score @s var_0 matches -40 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -52.80 ~
execute if score @s var_0 matches -39 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -52.03 ~
execute if score @s var_0 matches -38 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -51.26 ~
execute if score @s var_0 matches -37 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -50.49 ~
execute if score @s var_0 matches -36 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -49.71 ~
execute if score @s var_0 matches -35 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -48.93 ~
execute if score @s var_0 matches -34 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -48.15 ~
execute if score @s var_0 matches -33 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -47.37 ~
execute if score @s var_0 matches -32 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -46.59 ~
execute if score @s var_0 matches -31 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -45.80 ~
execute if score @s var_0 matches -30 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -45.02 ~
execute if score @s var_0 matches -29 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -44.23 ~
execute if score @s var_0 matches -28 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -43.44 ~
execute if score @s var_0 matches -27 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -42.64 ~
execute if score @s var_0 matches -26 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -41.85 ~
execute if score @s var_0 matches -25 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -41.05 ~
execute if score @s var_0 matches -24 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -40.45 ~
execute if score @s var_0 matches -23 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -39.44 ~
execute if score @s var_0 matches -22 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -38.64 ~
execute if score @s var_0 matches -21 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -37.83 ~
execute if score @s var_0 matches -20 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -37.02 ~
execute if score @s var_0 matches -19 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -36.20 ~
execute if score @s var_0 matches -18 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -35.39 ~
execute if score @s var_0 matches -17 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -34.57 ~
execute if score @s var_0 matches -16 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -33.75 ~
execute if score @s var_0 matches -15 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -32.92 ~
execute if score @s var_0 matches -14 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -32.09 ~
execute if score @s var_0 matches -13 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -31.26 ~
execute if score @s var_0 matches -12 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -30.43 ~
execute if score @s var_0 matches -11 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -29.59 ~
execute if score @s var_0 matches -10 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -28.75 ~
execute if score @s var_0 matches -9 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -27.90 ~
execute if score @s var_0 matches -8 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -27.05 ~
execute if score @s var_0 matches -7 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -26.20 ~
execute if score @s var_0 matches -6 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -25.35 ~
execute if score @s var_0 matches -5 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -24.49 ~
execute if score @s var_0 matches -4 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -23.63 ~
execute if score @s var_0 matches -3 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -22.76 ~
execute if score @s var_0 matches -2 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -21.89 ~
execute if score @s var_0 matches -1 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -21.01 ~
execute if score @s var_0 matches 0 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -20.23 ~
execute if score @s var_0 matches 1 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -19.25 ~
execute if score @s var_0 matches 2 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -18.36 ~
execute if score @s var_0 matches 3 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -17.47 ~
execute if score @s var_0 matches 4 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -16.57 ~
execute if score @s var_0 matches 5 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -15.67 ~
execute if score @s var_0 matches 6 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -14.76 ~
execute if score @s var_0 matches 7 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -13.85 ~
execute if score @s var_0 matches 8 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -12.93 ~
execute if score @s var_0 matches 9 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -12.01 ~
execute if score @s var_0 matches 10 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -11.09 ~
execute if score @s var_0 matches 11 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -10.25 ~
execute if score @s var_0 matches 12 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -9.22 ~
execute if score @s var_0 matches 13 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -8.27 ~
execute if score @s var_0 matches 14 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -7.32 ~
execute if score @s var_0 matches 15 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -6.37 ~
execute if score @s var_0 matches 16 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -5.41 ~
execute if score @s var_0 matches 17 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -4.44 ~
execute if score @s var_0 matches 18 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -3.47 ~
execute if score @s var_0 matches 19 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -2.49 ~
execute if score @s var_0 matches 20 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -1.50 ~
execute if score @s var_0 matches 21 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot -0.51 ~
execute if score @s var_0 matches 22 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 0.48 ~
execute if score @s var_0 matches 23 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 1.49 ~
execute if score @s var_0 matches 24 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 2.50 ~
execute if score @s var_0 matches 25 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 3.53 ~
execute if score @s var_0 matches 26 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 4.55 ~
execute if score @s var_0 matches 27 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 5.59 ~
execute if score @s var_0 matches 28 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 6.63 ~
execute if score @s var_0 matches 29 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 7.69 ~
execute if score @s var_0 matches 30 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 8.75 ~
execute if score @s var_0 matches 31 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 9.81 ~
execute if score @s var_0 matches 32 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 10.89 ~
execute if score @s var_0 matches 33 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 11.97 ~
execute if score @s var_0 matches 34 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 13.07 ~
execute if score @s var_0 matches 35 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 14.17 ~
execute if score @s var_0 matches 36 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 15.28 ~
execute if score @s var_0 matches 37 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 16.40 ~
execute if score @s var_0 matches 38 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 17.53 ~
execute if score @s var_0 matches 39 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 18.67 ~
execute if score @s var_0 matches 40 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 19.81 ~
execute if score @s var_0 matches 41 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 20.97 ~
execute if score @s var_0 matches 42 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 22.14 ~
execute if score @s var_0 matches 43 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 23.32 ~
execute if score @s var_0 matches 44 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 24.50 ~
execute if score @s var_0 matches 45 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 25.70 ~
execute if score @s var_0 matches 46 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 26.91 ~
execute if score @s var_0 matches 47 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 28.13 ~
execute if score @s var_0 matches 48 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 29.36 ~
execute if score @s var_0 matches 49 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 30.60 ~
execute if score @s var_0 matches 50 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 31.85 ~
execute if score @s var_0 matches 51 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 33.11 ~
execute if score @s var_0 matches 52 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 34.38 ~
execute if score @s var_0 matches 53 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 35.66 ~
execute if score @s var_0 matches 54 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 36.96 ~
execute if score @s var_0 matches 55 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 38.26 ~
execute if score @s var_0 matches 56 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 39.58 ~
execute if score @s var_0 matches 57 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 40.91 ~
execute if score @s var_0 matches 58 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 42.25 ~
execute if score @s var_0 matches 59 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 43.60 ~
execute if score @s var_0 matches 60 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 44.96 ~
execute if score @s var_0 matches 61 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 46.33 ~
execute if score @s var_0 matches 62 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 47.71 ~
execute if score @s var_0 matches 63 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 49.11 ~
execute if score @s var_0 matches 64 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 50.51 ~
execute if score @s var_0 matches 65 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 51.93 ~
execute if score @s var_0 matches 66 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 53.35 ~
execute if score @s var_0 matches 67 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 54.79 ~
execute if score @s var_0 matches 68 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 56.24 ~
execute if score @s var_0 matches 69 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 57.69 ~
execute if score @s var_0 matches 70 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 59.16 ~
execute if score @s var_0 matches 71 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 60.64 ~
execute if score @s var_0 matches 72 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 62.12 ~
execute if score @s var_0 matches 73 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 63.62 ~
execute if score @s var_0 matches 74 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 65.12 ~
execute if score @s var_0 matches 75 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 66.63 ~
execute if score @s var_0 matches 76 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 68.15 ~
execute if score @s var_0 matches 77 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 69.68 ~
execute if score @s var_0 matches 78 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 71.22 ~
execute if score @s var_0 matches 79 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 72.76 ~
execute if score @s var_0 matches 80 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 74.30 ~
execute if score @s var_0 matches 81 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 75.86 ~
execute if score @s var_0 matches 82 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 77.41 ~
execute if score @s var_0 matches 83 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 78.98 ~
execute if score @s var_0 matches 84 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 80.54 ~
execute if score @s var_0 matches 85 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 82.11 ~
execute if score @s var_0 matches 86 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 83.69 ~
execute if score @s var_0 matches 87 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 85.26 ~
execute if score @s var_0 matches 88 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 86.84 ~
execute if score @s var_0 matches 89 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 88.42 ~
execute if score @s var_0 matches 90 rotated ~ 0 positioned ^ ^0.4 ^0.2 run camera @s set minecraft:free ease 0.2 out_circ pos ~ ~ ~ rot 90 ~
