replaceitem entity @s slot.chest 0 destroy air 1 0
replaceitem entity @s slot.chest 1 destroy air 1 0
replaceitem entity @s slot.chest 2 destroy air 1 0
replaceitem entity @s slot.chest 3 destroy air 1 0
replaceitem entity @s slot.chest 4 destroy air 1 0
replaceitem entity @s slot.chest 5 destroy air 1 0
replaceitem entity @s slot.chest 6 destroy air 1 0
replaceitem entity @s slot.chest 7 destroy air 1 0
replaceitem entity @s slot.chest 8 destroy air 1 0
replaceitem entity @s slot.chest 9 destroy air 1 0
replaceitem entity @s slot.chest 10 destroy air 1 0
replaceitem entity @s slot.chest 11 destroy air 1 0
replaceitem entity @s slot.chest 12 destroy air 1 0
replaceitem entity @s slot.chest 13 destroy air 1 0
replaceitem entity @s slot.chest 14 destroy air 1 0
