replaceitem entity @s slot.inventory 0 destroy air 1 0
replaceitem entity @s slot.inventory 1 destroy air 1 0
replaceitem entity @s slot.inventory 2 destroy air 1 0
replaceitem entity @s slot.inventory 3 destroy air 1 0
replaceitem entity @s slot.inventory 4 destroy air 1 0
replaceitem entity @s slot.inventory 5 destroy air 1 0
replaceitem entity @s slot.inventory 6 destroy air 1 0
replaceitem entity @s slot.inventory 7 destroy air 1 0
replaceitem entity @s slot.inventory 8 destroy air 1 0
replaceitem entity @s slot.inventory 9 destroy air 1 0
replaceitem entity @s slot.inventory 10 destroy air 1 0
replaceitem entity @s slot.inventory 11 destroy air 1 0
replaceitem entity @s slot.inventory 12 destroy air 1 0
replaceitem entity @s slot.inventory 13 destroy air 1 0
replaceitem entity @s slot.inventory 14 destroy air 1 0
replaceitem entity @s slot.inventory 15 destroy air 1 0
replaceitem entity @s slot.inventory 16 destroy air 1 0
replaceitem entity @s slot.inventory 17 destroy air 1 0
replaceitem entity @s slot.inventory 18 destroy air 1 0
replaceitem entity @s slot.inventory 19 destroy air 1 0
replaceitem entity @s slot.inventory 20 destroy air 1 0
replaceitem entity @s slot.inventory 21 destroy air 1 0
replaceitem entity @s slot.inventory 22 destroy air 1 0
replaceitem entity @s slot.inventory 23 destroy air 1 0
replaceitem entity @s slot.inventory 24 destroy air 1 0
replaceitem entity @s slot.inventory 25 destroy air 1 0
replaceitem entity @s slot.inventory 26 destroy air 1 0
