function operation/clear/inventory
replaceitem entity @s slot.enderchest 0 destroy air 1 0
replaceitem entity @s slot.enderchest 1 destroy air 1 0
replaceitem entity @s slot.enderchest 2 destroy air 1 0
replaceitem entity @s slot.enderchest 3 destroy air 1 0
replaceitem entity @s slot.enderchest 4 destroy air 1 0
replaceitem entity @s slot.enderchest 5 destroy air 1 0
replaceitem entity @s slot.enderchest 6 destroy air 1 0
replaceitem entity @s slot.enderchest 7 destroy air 1 0
replaceitem entity @s slot.enderchest 8 destroy air 1 0
replaceitem entity @s slot.enderchest 9 destroy air 1 0
replaceitem entity @s slot.enderchest 10 destroy air 1 0
replaceitem entity @s slot.enderchest 11 destroy air 1 0
replaceitem entity @s slot.enderchest 12 destroy air 1 0
replaceitem entity @s slot.enderchest 13 destroy air 1 0
replaceitem entity @s slot.enderchest 14 destroy air 1 0
replaceitem entity @s slot.enderchest 15 destroy air 1 0
replaceitem entity @s slot.enderchest 16 destroy air 1 0
replaceitem entity @s slot.enderchest 17 destroy air 1 0
replaceitem entity @s slot.enderchest 18 destroy air 1 0
replaceitem entity @s slot.enderchest 19 destroy air 1 0
replaceitem entity @s slot.enderchest 20 destroy air 1 0
replaceitem entity @s slot.enderchest 21 destroy air 1 0
replaceitem entity @s slot.enderchest 22 destroy air 1 0
replaceitem entity @s slot.enderchest 23 destroy air 1 0
replaceitem entity @s slot.enderchest 24 destroy air 1 0
replaceitem entity @s slot.enderchest 25 destroy air 1 0
replaceitem entity @s slot.enderchest 26 destroy air 1 0
replaceitem entity @s slot.hotbar 0 destroy air 1 0
replaceitem entity @s slot.hotbar 1 destroy air 1 0
replaceitem entity @s slot.hotbar 2 destroy air 1 0
replaceitem entity @s slot.hotbar 3 destroy air 1 0
replaceitem entity @s slot.hotbar 4 destroy air 1 0
replaceitem entity @s slot.hotbar 5 destroy air 1 0
replaceitem entity @s slot.hotbar 6 destroy air 1 0
replaceitem entity @s slot.hotbar 7 destroy air 1 0
replaceitem entity @s slot.hotbar 8 destroy air 1 0
