replaceitem entity @s slot.enderchest 0 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 1 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 2 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 3 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 4 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 5 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 6 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 7 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 8 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 9 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 10 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 11 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 12 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 13 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 14 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 15 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 16 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 17 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 18 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 19 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 20 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 21 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 22 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 23 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 24 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 25 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @s slot.enderchest 26 destroy yoni:empty_slot 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
