execute @s[scores={plight:type=208,plight=!14}] ~ ~ ~ scoreboard players set @s plight 14
execute @s[scores={plight:type=1,plight=!0}] ~ ~ ~ scoreboard players set @s plight 0
execute @s[scores={plight:type=89,plight=!15}] ~ ~ ~ scoreboard players set @s plight 15
execute @s[scores={plight:type=138,plight=!15}] ~ ~ ~ scoreboard players set @s plight 15
execute @s[scores={plight:type=91,plight=!9}] ~ ~ ~ scoreboard players set @s plight 9
execute @s[scores={plight:type=213,plight=!0}] ~ ~ ~ scoreboard players set @s plight 0
execute @s[scores={plight:type=771,plight=!5}] ~ ~ ~ scoreboard players set @s plight 5
execute @s[scores={plight:type=116,plight=!5}] ~ ~ ~ scoreboard players set @s plight 5
execute @s[scores={plight:type=-208,plight=!0}] ~ ~ ~ scoreboard players set @s plight 0
execute @s[scores={plight:type=-269,plight=!10}] ~ ~ ~ scoreboard players set @s plight 10
execute @s[scores={plight:type=-230,plight=!13}] ~ ~ ~ scoreboard players set @s plight 13
execute @s[scores={plight:type=-157,plight=!15}] ~ ~ ~ scoreboard players set @s plight 15
execute @s[scores={plight:type=169,plight=!15}] ~ ~ ~ scoreboard players set @s plight 15
execute @s[scores={plight:type=325,plight=!0}] ~ ~ ~ scoreboard players set @s plight 0
execute @s[scores={plight:type=76,plight=!7}] ~ ~ ~ scoreboard players set @s plight 7
execute @s[scores={plight:type=-289,plight=!7}] ~ ~ ~ scoreboard players set @s plight 7
