# This is a basic workflow to help you get started with Actions

name: YoniMC CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the yonimc branch
  push:
    branches: [ yonimc ]
  pull_request:
    branches: [ yonimc ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE/games/com.mojang/development_behavior_packs/YoniMC/
          zip -r "$GITHUB_WORKSPACE"/yonimc-ci.mcpack *
